/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 39
#define LARGE_STATE_COUNT 18
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_number = 2,
  anon_sym_DQUOTE = 3,
  aux_sym_string_token1 = 4,
  anon_sym_BSLASH = 5,
  anon_sym_n = 6,
  anon_sym_t = 7,
  anon_sym_r = 8,
  anon_sym_DOLLAR = 9,
  anon_sym_DOLLAR2 = 10,
  sym_string_interpolation = 11,
  anon_sym_DOLLAR_LPAREN = 12,
  anon_sym_RPAREN = 13,
  sym_keyword = 14,
  sym_symbol = 15,
  anon_sym_SQUOTE = 16,
  anon_sym_BQUOTE = 17,
  anon_sym_TILDE = 18,
  anon_sym_TILDE_AT = 19,
  anon_sym_LPAREN = 20,
  anon_sym_LBRACK = 21,
  anon_sym_RBRACK = 22,
  anon_sym_LBRACE = 23,
  anon_sym_RBRACE = 24,
  sym_source_file = 25,
  sym__form = 26,
  sym_string = 27,
  sym_string_expression = 28,
  sym_quote = 29,
  sym_quasiquote = 30,
  sym_unquote = 31,
  sym_unquote_splice = 32,
  sym_list = 33,
  sym_vector = 34,
  sym_map = 35,
  aux_sym_source_file_repeat1 = 36,
  aux_sym_string_repeat1 = 37,
  aux_sym_map_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_n] = "n",
  [anon_sym_t] = "t",
  [anon_sym_r] = "r",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_DOLLAR2] = "$",
  [sym_string_interpolation] = "string_interpolation",
  [anon_sym_DOLLAR_LPAREN] = "$(",
  [anon_sym_RPAREN] = ")",
  [sym_keyword] = "keyword",
  [sym_symbol] = "symbol",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_TILDE] = "~",
  [anon_sym_TILDE_AT] = "~@",
  [anon_sym_LPAREN] = "(",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_source_file] = "source_file",
  [sym__form] = "_form",
  [sym_string] = "string",
  [sym_string_expression] = "string_expression",
  [sym_quote] = "quote",
  [sym_quasiquote] = "quasiquote",
  [sym_unquote] = "unquote",
  [sym_unquote_splice] = "unquote_splice",
  [sym_list] = "list",
  [sym_vector] = "vector",
  [sym_map] = "map",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_map_repeat1] = "map_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_n] = anon_sym_n,
  [anon_sym_t] = anon_sym_t,
  [anon_sym_r] = anon_sym_r,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_DOLLAR2] = anon_sym_DOLLAR,
  [sym_string_interpolation] = sym_string_interpolation,
  [anon_sym_DOLLAR_LPAREN] = anon_sym_DOLLAR_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_keyword] = sym_keyword,
  [sym_symbol] = sym_symbol,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_TILDE_AT] = anon_sym_TILDE_AT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_source_file] = sym_source_file,
  [sym__form] = sym__form,
  [sym_string] = sym_string,
  [sym_string_expression] = sym_string_expression,
  [sym_quote] = sym_quote,
  [sym_quasiquote] = sym_quasiquote,
  [sym_unquote] = sym_unquote,
  [sym_unquote_splice] = sym_unquote_splice,
  [sym_list] = sym_list,
  [sym_vector] = sym_vector,
  [sym_map] = sym_map,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_map_repeat1] = aux_sym_map_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_n] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_t] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_r] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR2] = {
    .visible = true,
    .named = false,
  },
  [sym_string_interpolation] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__form] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_quasiquote] = {
    .visible = true,
    .named = true,
  },
  [sym_unquote] = {
    .visible = true,
    .named = true,
  },
  [sym_unquote_splice] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_vector] = {
    .visible = true,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_map_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
};

static const TSCharacterRange sym_string_interpolation_character_set_1[] = {
  {'!', '!'}, {'#', '#'}, {'&', '&'}, {'*', '+'}, {'-', '9'}, {'<', '?'}, {'A', 'Z'}, {'_', '_'},
  {'a', 'z'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '"', 11,
        '$', 20,
        '\'', 28,
        '(', 32,
        ')', 24,
        '-', 3,
        ':', 4,
        ';', 8,
        '[', 33,
        '\\', 15,
        ']', 34,
        '`', 29,
        'n', 16,
        'r', 18,
        't', 17,
        '{', 35,
        '}', 36,
        '~', 30,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(11);
      if (lookahead == '$') ADVANCE(19);
      if (lookahead == ';') ADVANCE(8);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead == 'n') ADVANCE(16);
      if (lookahead == 'r') ADVANCE(18);
      if (lookahead == 't') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(11);
      if (lookahead == '$') ADVANCE(21);
      if (lookahead == ';') ADVANCE(12);
      if (lookahead == '\\') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 4:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 5:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '"', 11,
        '$', 19,
        '\'', 28,
        '(', 32,
        ')', 24,
        '-', 3,
        ':', 4,
        ';', 8,
        '[', 33,
        '\\', 15,
        ']', 34,
        '`', 29,
        'n', 16,
        'r', 18,
        't', 17,
        '{', 35,
        '}', 36,
        '~', 30,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      ADVANCE_MAP(
        '"', 11,
        '\'', 28,
        '(', 32,
        ')', 24,
        '-', 26,
        ':', 4,
        ';', 8,
        '[', 33,
        ']', 34,
        '`', 29,
        '{', 35,
        '}', 36,
        '~', 30,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      if (lookahead == '!' ||
          lookahead == '*' ||
          lookahead == '+' ||
          ('/' <= lookahead && lookahead <= '?') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (set_contains(sym_string_interpolation_character_set_1, 9, lookahead)) ADVANCE(27);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '"' ||
          lookahead == '$' ||
          lookahead == '\\') ADVANCE(8);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == ';') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_n);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_t);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_r);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DOLLAR2);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DOLLAR2);
      if (lookahead == '(') ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_string_interpolation);
      if (set_contains(sym_string_interpolation_character_set_1, 9, lookahead)) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_keyword);
      if ((set_contains(sym_string_interpolation_character_set_1, 9, lookahead)) &&
          lookahead != '#' &&
          lookahead != '&' &&
          lookahead != '+' &&
          lookahead != '.' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (set_contains(sym_string_interpolation_character_set_1, 9, lookahead)) ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_symbol);
      if (set_contains(sym_string_interpolation_character_set_1, 9, lookahead)) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_TILDE);
      if (lookahead == '@') ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_TILDE_AT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_n] = ACTIONS(1),
    [anon_sym_t] = ACTIONS(1),
    [anon_sym_r] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_DOLLAR2] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_keyword] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_TILDE_AT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(38),
    [sym__form] = STATE(6),
    [sym_string] = STATE(6),
    [sym_quote] = STATE(6),
    [sym_quasiquote] = STATE(6),
    [sym_unquote] = STATE(6),
    [sym_unquote_splice] = STATE(6),
    [sym_list] = STATE(6),
    [sym_vector] = STATE(6),
    [sym_map] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [sym_number] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_keyword] = ACTIONS(7),
    [sym_symbol] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_BQUOTE] = ACTIONS(15),
    [anon_sym_TILDE] = ACTIONS(17),
    [anon_sym_TILDE_AT] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(25),
  },
  [STATE(2)] = {
    [sym__form] = STATE(2),
    [sym_string] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_quasiquote] = STATE(2),
    [sym_unquote] = STATE(2),
    [sym_unquote_splice] = STATE(2),
    [sym_list] = STATE(2),
    [sym_vector] = STATE(2),
    [sym_map] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_comment] = ACTIONS(29),
    [sym_number] = ACTIONS(32),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_RPAREN] = ACTIONS(27),
    [sym_keyword] = ACTIONS(29),
    [sym_symbol] = ACTIONS(32),
    [anon_sym_SQUOTE] = ACTIONS(38),
    [anon_sym_BQUOTE] = ACTIONS(41),
    [anon_sym_TILDE] = ACTIONS(44),
    [anon_sym_TILDE_AT] = ACTIONS(47),
    [anon_sym_LPAREN] = ACTIONS(50),
    [anon_sym_LBRACK] = ACTIONS(53),
    [anon_sym_RBRACK] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(56),
  },
  [STATE(3)] = {
    [sym__form] = STATE(17),
    [sym_string] = STATE(17),
    [sym_quote] = STATE(17),
    [sym_quasiquote] = STATE(17),
    [sym_unquote] = STATE(17),
    [sym_unquote_splice] = STATE(17),
    [sym_list] = STATE(17),
    [sym_vector] = STATE(17),
    [sym_map] = STATE(17),
    [aux_sym_map_repeat1] = STATE(11),
    [sym_comment] = ACTIONS(59),
    [sym_number] = ACTIONS(61),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_keyword] = ACTIONS(59),
    [sym_symbol] = ACTIONS(61),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_BQUOTE] = ACTIONS(15),
    [anon_sym_TILDE] = ACTIONS(17),
    [anon_sym_TILDE_AT] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(63),
  },
  [STATE(4)] = {
    [sym__form] = STATE(9),
    [sym_string] = STATE(9),
    [sym_quote] = STATE(9),
    [sym_quasiquote] = STATE(9),
    [sym_unquote] = STATE(9),
    [sym_unquote_splice] = STATE(9),
    [sym_list] = STATE(9),
    [sym_vector] = STATE(9),
    [sym_map] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [sym_comment] = ACTIONS(65),
    [sym_number] = ACTIONS(67),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(69),
    [sym_keyword] = ACTIONS(65),
    [sym_symbol] = ACTIONS(67),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_BQUOTE] = ACTIONS(15),
    [anon_sym_TILDE] = ACTIONS(17),
    [anon_sym_TILDE_AT] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(25),
  },
  [STATE(5)] = {
    [sym__form] = STATE(8),
    [sym_string] = STATE(8),
    [sym_quote] = STATE(8),
    [sym_quasiquote] = STATE(8),
    [sym_unquote] = STATE(8),
    [sym_unquote_splice] = STATE(8),
    [sym_list] = STATE(8),
    [sym_vector] = STATE(8),
    [sym_map] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [sym_comment] = ACTIONS(71),
    [sym_number] = ACTIONS(73),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_keyword] = ACTIONS(71),
    [sym_symbol] = ACTIONS(73),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_BQUOTE] = ACTIONS(15),
    [anon_sym_TILDE] = ACTIONS(17),
    [anon_sym_TILDE_AT] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_RBRACK] = ACTIONS(75),
    [anon_sym_LBRACE] = ACTIONS(25),
  },
  [STATE(6)] = {
    [sym__form] = STATE(2),
    [sym_string] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_quasiquote] = STATE(2),
    [sym_unquote] = STATE(2),
    [sym_unquote_splice] = STATE(2),
    [sym_list] = STATE(2),
    [sym_vector] = STATE(2),
    [sym_map] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(77),
    [sym_comment] = ACTIONS(79),
    [sym_number] = ACTIONS(81),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_keyword] = ACTIONS(79),
    [sym_symbol] = ACTIONS(81),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_BQUOTE] = ACTIONS(15),
    [anon_sym_TILDE] = ACTIONS(17),
    [anon_sym_TILDE_AT] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(25),
  },
  [STATE(7)] = {
    [sym__form] = STATE(12),
    [sym_string] = STATE(12),
    [sym_quote] = STATE(12),
    [sym_quasiquote] = STATE(12),
    [sym_unquote] = STATE(12),
    [sym_unquote_splice] = STATE(12),
    [sym_list] = STATE(12),
    [sym_vector] = STATE(12),
    [sym_map] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(12),
    [sym_comment] = ACTIONS(83),
    [sym_number] = ACTIONS(85),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(87),
    [sym_keyword] = ACTIONS(83),
    [sym_symbol] = ACTIONS(85),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_BQUOTE] = ACTIONS(15),
    [anon_sym_TILDE] = ACTIONS(17),
    [anon_sym_TILDE_AT] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(25),
  },
  [STATE(8)] = {
    [sym__form] = STATE(2),
    [sym_string] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_quasiquote] = STATE(2),
    [sym_unquote] = STATE(2),
    [sym_unquote_splice] = STATE(2),
    [sym_list] = STATE(2),
    [sym_vector] = STATE(2),
    [sym_map] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_comment] = ACTIONS(79),
    [sym_number] = ACTIONS(81),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_keyword] = ACTIONS(79),
    [sym_symbol] = ACTIONS(81),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_BQUOTE] = ACTIONS(15),
    [anon_sym_TILDE] = ACTIONS(17),
    [anon_sym_TILDE_AT] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_RBRACK] = ACTIONS(89),
    [anon_sym_LBRACE] = ACTIONS(25),
  },
  [STATE(9)] = {
    [sym__form] = STATE(2),
    [sym_string] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_quasiquote] = STATE(2),
    [sym_unquote] = STATE(2),
    [sym_unquote_splice] = STATE(2),
    [sym_list] = STATE(2),
    [sym_vector] = STATE(2),
    [sym_map] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_comment] = ACTIONS(79),
    [sym_number] = ACTIONS(81),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(91),
    [sym_keyword] = ACTIONS(79),
    [sym_symbol] = ACTIONS(81),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_BQUOTE] = ACTIONS(15),
    [anon_sym_TILDE] = ACTIONS(17),
    [anon_sym_TILDE_AT] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(25),
  },
  [STATE(10)] = {
    [sym__form] = STATE(17),
    [sym_string] = STATE(17),
    [sym_quote] = STATE(17),
    [sym_quasiquote] = STATE(17),
    [sym_unquote] = STATE(17),
    [sym_unquote_splice] = STATE(17),
    [sym_list] = STATE(17),
    [sym_vector] = STATE(17),
    [sym_map] = STATE(17),
    [aux_sym_map_repeat1] = STATE(10),
    [sym_comment] = ACTIONS(93),
    [sym_number] = ACTIONS(96),
    [anon_sym_DQUOTE] = ACTIONS(99),
    [sym_keyword] = ACTIONS(93),
    [sym_symbol] = ACTIONS(96),
    [anon_sym_SQUOTE] = ACTIONS(102),
    [anon_sym_BQUOTE] = ACTIONS(105),
    [anon_sym_TILDE] = ACTIONS(108),
    [anon_sym_TILDE_AT] = ACTIONS(111),
    [anon_sym_LPAREN] = ACTIONS(114),
    [anon_sym_LBRACK] = ACTIONS(117),
    [anon_sym_LBRACE] = ACTIONS(120),
    [anon_sym_RBRACE] = ACTIONS(123),
  },
  [STATE(11)] = {
    [sym__form] = STATE(17),
    [sym_string] = STATE(17),
    [sym_quote] = STATE(17),
    [sym_quasiquote] = STATE(17),
    [sym_unquote] = STATE(17),
    [sym_unquote_splice] = STATE(17),
    [sym_list] = STATE(17),
    [sym_vector] = STATE(17),
    [sym_map] = STATE(17),
    [aux_sym_map_repeat1] = STATE(10),
    [sym_comment] = ACTIONS(59),
    [sym_number] = ACTIONS(61),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_keyword] = ACTIONS(59),
    [sym_symbol] = ACTIONS(61),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_BQUOTE] = ACTIONS(15),
    [anon_sym_TILDE] = ACTIONS(17),
    [anon_sym_TILDE_AT] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(125),
  },
  [STATE(12)] = {
    [sym__form] = STATE(2),
    [sym_string] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_quasiquote] = STATE(2),
    [sym_unquote] = STATE(2),
    [sym_unquote_splice] = STATE(2),
    [sym_list] = STATE(2),
    [sym_vector] = STATE(2),
    [sym_map] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_comment] = ACTIONS(79),
    [sym_number] = ACTIONS(81),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(127),
    [sym_keyword] = ACTIONS(79),
    [sym_symbol] = ACTIONS(81),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_BQUOTE] = ACTIONS(15),
    [anon_sym_TILDE] = ACTIONS(17),
    [anon_sym_TILDE_AT] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(25),
  },
  [STATE(13)] = {
    [sym__form] = STATE(27),
    [sym_string] = STATE(27),
    [sym_quote] = STATE(27),
    [sym_quasiquote] = STATE(27),
    [sym_unquote] = STATE(27),
    [sym_unquote_splice] = STATE(27),
    [sym_list] = STATE(27),
    [sym_vector] = STATE(27),
    [sym_map] = STATE(27),
    [sym_comment] = ACTIONS(129),
    [sym_number] = ACTIONS(131),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_keyword] = ACTIONS(129),
    [sym_symbol] = ACTIONS(131),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_BQUOTE] = ACTIONS(15),
    [anon_sym_TILDE] = ACTIONS(17),
    [anon_sym_TILDE_AT] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(25),
  },
  [STATE(14)] = {
    [sym__form] = STATE(25),
    [sym_string] = STATE(25),
    [sym_quote] = STATE(25),
    [sym_quasiquote] = STATE(25),
    [sym_unquote] = STATE(25),
    [sym_unquote_splice] = STATE(25),
    [sym_list] = STATE(25),
    [sym_vector] = STATE(25),
    [sym_map] = STATE(25),
    [sym_comment] = ACTIONS(133),
    [sym_number] = ACTIONS(135),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_keyword] = ACTIONS(133),
    [sym_symbol] = ACTIONS(135),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_BQUOTE] = ACTIONS(15),
    [anon_sym_TILDE] = ACTIONS(17),
    [anon_sym_TILDE_AT] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(25),
  },
  [STATE(15)] = {
    [sym__form] = STATE(18),
    [sym_string] = STATE(18),
    [sym_quote] = STATE(18),
    [sym_quasiquote] = STATE(18),
    [sym_unquote] = STATE(18),
    [sym_unquote_splice] = STATE(18),
    [sym_list] = STATE(18),
    [sym_vector] = STATE(18),
    [sym_map] = STATE(18),
    [sym_comment] = ACTIONS(137),
    [sym_number] = ACTIONS(139),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_keyword] = ACTIONS(137),
    [sym_symbol] = ACTIONS(139),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_BQUOTE] = ACTIONS(15),
    [anon_sym_TILDE] = ACTIONS(17),
    [anon_sym_TILDE_AT] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(25),
  },
  [STATE(16)] = {
    [sym__form] = STATE(19),
    [sym_string] = STATE(19),
    [sym_quote] = STATE(19),
    [sym_quasiquote] = STATE(19),
    [sym_unquote] = STATE(19),
    [sym_unquote_splice] = STATE(19),
    [sym_list] = STATE(19),
    [sym_vector] = STATE(19),
    [sym_map] = STATE(19),
    [sym_comment] = ACTIONS(141),
    [sym_number] = ACTIONS(143),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_keyword] = ACTIONS(141),
    [sym_symbol] = ACTIONS(143),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_BQUOTE] = ACTIONS(15),
    [anon_sym_TILDE] = ACTIONS(17),
    [anon_sym_TILDE_AT] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(25),
  },
  [STATE(17)] = {
    [sym__form] = STATE(30),
    [sym_string] = STATE(30),
    [sym_quote] = STATE(30),
    [sym_quasiquote] = STATE(30),
    [sym_unquote] = STATE(30),
    [sym_unquote_splice] = STATE(30),
    [sym_list] = STATE(30),
    [sym_vector] = STATE(30),
    [sym_map] = STATE(30),
    [sym_comment] = ACTIONS(145),
    [sym_number] = ACTIONS(147),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [sym_keyword] = ACTIONS(145),
    [sym_symbol] = ACTIONS(147),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_BQUOTE] = ACTIONS(15),
    [anon_sym_TILDE] = ACTIONS(17),
    [anon_sym_TILDE_AT] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(151), 3,
      sym_number,
      sym_symbol,
      anon_sym_TILDE,
    ACTIONS(149), 13,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      sym_keyword,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_TILDE_AT,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [21] = 2,
    ACTIONS(155), 3,
      sym_number,
      sym_symbol,
      anon_sym_TILDE,
    ACTIONS(153), 13,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      sym_keyword,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_TILDE_AT,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [42] = 2,
    ACTIONS(159), 3,
      sym_number,
      sym_symbol,
      anon_sym_TILDE,
    ACTIONS(157), 13,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      sym_keyword,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_TILDE_AT,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [63] = 2,
    ACTIONS(163), 3,
      sym_number,
      sym_symbol,
      anon_sym_TILDE,
    ACTIONS(161), 13,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      sym_keyword,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_TILDE_AT,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [84] = 2,
    ACTIONS(167), 3,
      sym_number,
      sym_symbol,
      anon_sym_TILDE,
    ACTIONS(165), 13,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      sym_keyword,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_TILDE_AT,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [105] = 2,
    ACTIONS(171), 3,
      sym_number,
      sym_symbol,
      anon_sym_TILDE,
    ACTIONS(169), 13,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      sym_keyword,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_TILDE_AT,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [126] = 2,
    ACTIONS(175), 3,
      sym_number,
      sym_symbol,
      anon_sym_TILDE,
    ACTIONS(173), 13,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      sym_keyword,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_TILDE_AT,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [147] = 2,
    ACTIONS(179), 3,
      sym_number,
      sym_symbol,
      anon_sym_TILDE,
    ACTIONS(177), 13,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      sym_keyword,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_TILDE_AT,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [168] = 2,
    ACTIONS(183), 3,
      sym_number,
      sym_symbol,
      anon_sym_TILDE,
    ACTIONS(181), 13,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      sym_keyword,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_TILDE_AT,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [189] = 2,
    ACTIONS(187), 3,
      sym_number,
      sym_symbol,
      anon_sym_TILDE,
    ACTIONS(185), 13,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      sym_keyword,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_TILDE_AT,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [210] = 2,
    ACTIONS(191), 3,
      sym_number,
      sym_symbol,
      anon_sym_TILDE,
    ACTIONS(189), 13,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      sym_keyword,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_TILDE_AT,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [231] = 2,
    ACTIONS(195), 3,
      sym_number,
      sym_symbol,
      anon_sym_TILDE,
    ACTIONS(193), 13,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      sym_keyword,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_TILDE_AT,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [252] = 2,
    ACTIONS(197), 3,
      sym_number,
      sym_symbol,
      anon_sym_TILDE,
    ACTIONS(123), 10,
      sym_comment,
      anon_sym_DQUOTE,
      sym_keyword,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      anon_sym_TILDE_AT,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [270] = 7,
    ACTIONS(199), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_DQUOTE,
    ACTIONS(205), 1,
      anon_sym_BSLASH,
    ACTIONS(207), 1,
      sym_string_interpolation,
    ACTIONS(209), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(203), 2,
      aux_sym_string_token1,
      anon_sym_DOLLAR2,
    STATE(32), 2,
      sym_string_expression,
      aux_sym_string_repeat1,
  [294] = 7,
    ACTIONS(199), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_BSLASH,
    ACTIONS(209), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(211), 1,
      anon_sym_DQUOTE,
    ACTIONS(215), 1,
      sym_string_interpolation,
    ACTIONS(213), 2,
      aux_sym_string_token1,
      anon_sym_DOLLAR2,
    STATE(33), 2,
      sym_string_expression,
      aux_sym_string_repeat1,
  [318] = 7,
    ACTIONS(199), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_DQUOTE,
    ACTIONS(222), 1,
      anon_sym_BSLASH,
    ACTIONS(225), 1,
      sym_string_interpolation,
    ACTIONS(228), 1,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(219), 2,
      aux_sym_string_token1,
      anon_sym_DOLLAR2,
    STATE(33), 2,
      sym_string_expression,
      aux_sym_string_repeat1,
  [342] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 6,
      anon_sym_DQUOTE,
      anon_sym_BSLASH,
      anon_sym_n,
      anon_sym_t,
      anon_sym_r,
      anon_sym_DOLLAR,
  [354] = 3,
    ACTIONS(199), 1,
      sym_comment,
    ACTIONS(233), 2,
      sym_string_interpolation,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(217), 4,
      anon_sym_DQUOTE,
      aux_sym_string_token1,
      anon_sym_BSLASH,
      anon_sym_DOLLAR2,
  [368] = 3,
    ACTIONS(199), 1,
      sym_comment,
    ACTIONS(237), 2,
      sym_string_interpolation,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(235), 4,
      anon_sym_DQUOTE,
      aux_sym_string_token1,
      anon_sym_BSLASH,
      anon_sym_DOLLAR2,
  [382] = 3,
    ACTIONS(199), 1,
      sym_comment,
    ACTIONS(241), 2,
      sym_string_interpolation,
      anon_sym_DOLLAR_LPAREN,
    ACTIONS(239), 4,
      anon_sym_DQUOTE,
      aux_sym_string_token1,
      anon_sym_BSLASH,
      anon_sym_DOLLAR2,
  [396] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(18)] = 0,
  [SMALL_STATE(19)] = 21,
  [SMALL_STATE(20)] = 42,
  [SMALL_STATE(21)] = 63,
  [SMALL_STATE(22)] = 84,
  [SMALL_STATE(23)] = 105,
  [SMALL_STATE(24)] = 126,
  [SMALL_STATE(25)] = 147,
  [SMALL_STATE(26)] = 168,
  [SMALL_STATE(27)] = 189,
  [SMALL_STATE(28)] = 210,
  [SMALL_STATE(29)] = 231,
  [SMALL_STATE(30)] = 252,
  [SMALL_STATE(31)] = 270,
  [SMALL_STATE(32)] = 294,
  [SMALL_STATE(33)] = 318,
  [SMALL_STATE(34)] = 342,
  [SMALL_STATE(35)] = 354,
  [SMALL_STATE(36)] = 368,
  [SMALL_STATE(37)] = 382,
  [SMALL_STATE(38)] = 396,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [108] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unquote_splice, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unquote_splice, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 3, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 3, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quasiquote, 2, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quasiquote, 2, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unquote, 2, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unquote, 2, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector, 3, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 3, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_map_repeat1, 2, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [219] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [222] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [228] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_expression, 2, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_expression, 2, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_expression, 3, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_expression, 3, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_luna(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "luna",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
